base_link:
  velodyne_rear_base_link:
    x: -0.09
    y: 0.0
    z: 0.45
    roll: 0.0
    pitch: 0.0
    yaw: 3.1415926535
  velodyne_top_base_link:
    x: 0.41
    y: 0.0
    z: 0.45
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.055
    y: 0.0
    z: 0.135
    roll: 0.0
    pitch: 0.0
    yaw: 3.1415926535
